### PR TITLE
Remove Windows carriage returns

### PR DESCRIPTION
**Pull request by turnerm**
Many of the files in this repo are full of Windows carriage returns which have been driving me a bit bonkers, this PR removes them. I just ran `dos2unix` on all files, which makes them all appear completely changed but I can assure you they are not, apart from adding both VSCode and PyCharm to the two `.gitignore`s.

### CODE REVIEW

**Comment by Tinkaa** [comment]
From a quick google, it looks fine. 
Do you know if it would cause any problems/be re-inserted if someone works from a Windows system?

**Comment by turnerm** [comment]
> Do you know if it would cause any problems/be re-inserted if someone works from a Windows system?

@Tinkaa That's a good question, I'm not sure. To be honest I'm wondering how it happend in the first place, I think a lot of people use windows for dev these days but I don't usually encounter many carriage returns floating around.

I should add though: If this was just in a normal repo I would be more inclined to ignore it. But since this will be creating all of our other repos I thought it best to nip it in the bud.

**Review by Tinkaa — APPROVED** [review]

**Comment by Tinkaa** [comment]
Alright. I think it is safe enough and smth that in the worst case we would figure out along the way. So imo can be merged

**Comment by caldwellst** [comment]
Looks safe to me, and interesting catch, never heard of it before! Maybe something we could eventually add to this repo that is generated when the cookie cutter is run is a `.gitattributes` file that ensure consistent returns across files, as described [here](https://stackoverflow.com/questions/170961/whats-the-strategy-for-handling-crlf-carriage-return-line-feed-with-git) and could deal with the issue @Tinkaa mentioned above!

**Review by caldwellst — APPROVED** [review]

**Pull request merged**
