### PR TITLE
Notebook linting

### PR DESCRIPTION
**Pull request by turnerm**
An attempt to address #3. 

I looked a bit into using `jupytext` and these types of things in pre-commit, and the main problem that I ran into is that pre-commit only runs on files that you will be committing, so I think that limits us a bit if we're not going to be committing the notebooks directly (which I don't think we should change). 

I still think it would be nice to have at least a bit of linting in our notebooks, so one option would be to pair with percent files (a type of Python file), after which `flake8` and `Black` can be run. The one tricky thing is that `isort` does not play well with this file type (I did some testing and you can end up with packages in the comments, etc), so for now I've listed it to not run in the `analysis` and `exploration` directories, not sure if there's a better way to to do this.

Finally,  a small bug fix: I've updated the second `.pre-commit-config` file to use the intended markdown linter. 

I'd be interested in hearing your thoughts, but also we might want to try and put this all in action -- I'll try to get `aa-toolbox` into PyPI soon so that we can start!

### CODE REVIEW

**Comment by caldwellst** [comment]
Interested to test the linting! Your explanation above makes a lot of sense, and the percent file linking sounds like a very cool workaround. I don't have any other comments on that but happy to test once we can build repos using this and put it into practice.

On the markdown linting, I think you've now switched it back to the old one, as we want to be using the Node.js markdown linter like in [pa-aa-toolbox](https://github.com/OCHA-DAP/pa-aa-toolbox/blob/develop/.pre-commit-config.yaml). Should also adjust the README to remove mention of Ruby as no longer necessary, although Node.js will be now (not sure if you need to manually install)?

**Comment by turnerm** [comment]
> On the markdown linting, I think you've now switched it back to the old one, as we want to be using the Node.js markdown linter like in pa-aa-toolbox. 

Hm now I am very confused. In the [files](https://github.com/OCHA-DAP/pa-aa-cookiecutter/pull/4/files) of that PR it looks like the switch was from `igorshubovych/markdownlint-cli` to `jumanjihouse/pre-commit-hooks` -- is that true? Was I a terrible code reviewer? Aha. At any rate I will fix this here!

> Should also adjust the README to remove mention of Ruby as no longer necessary, although Node.js will be now (not sure if you need to manually install)?

I was wondering that as well. I'll just remove the Ruby part for now, and as for `nodejs` it doesn't appear that I have it installed and it still seems to run for me.

**Review by Tinkaa — APPROVED** [review]
Sorry for the late reply. I like the idea and it sounds good to me. I haven't dived deeply into linting as of yet, so I trust you and Seth have a good enough understanding of it that all the code is fine

**Review by caldwellst — APPROVED** [review]
Monica and I had touched bilaterally about the issue with which linter which was essentially that Hannah likely changed to the Node.js version, and I missed that so changed it back to the Ruby version, and then Monica changed back to Node.js which I just inherently assumed was the Ruby version hahahaha. But all should be good now.

**Pull request merged**
