### PR TITLE
increase line-length

### PR DESCRIPTION
**Pull request by Tinkaa**
Implements #8

### CODE REVIEW

**Comment by turnerm** [comment]
@Tinkaa I thought that you wanted to increase the line length for the markdown. For the code itself we can also do it, but I would maybe go to 100 max, preferably 88 which is the Black default. 

If you do want to change the code line length, then you would also need to change it for `flake8` (in `.flake8rc`). Note that there is a pre-commit and flake8rc for the cookiecutter repo itself as well as the created repositories; I would make any changes consistent across both

**Comment by Tinkaa** [comment]
Ahaha I shouldn't do this late in the day (and see what I am doing now again). 

I did some research on how to add it for the markdownlinter. And this seems [to be the only way](https://github.com/jumanjihouse/pre-commit-hooks#markdownlint)

I am not a big fan of it, as it requires two extra files. Maybe that is not worth having this longer line-length after all. Do you have an opinion?

**Review by turnerm — APPROVED** [review]
> I did some research on how to add it for the markdownlinter. And this seems [to be the only way](https://github.com/jumanjihouse/pre-commit-hooks#markdownlint)

I've been trying to look into it although giving up for now, but do you think it could be possible to just pass a parameter directly in pre-commit? 

> I am not a big fan of it, as it requires two extra files. Maybe that is not worth having this longer line-length after all. Do you have an opinion?

I'm fine with the 80 char limit myself, I think you'll probably be working more with this repos than I will, so I'll leave it up to you. You could also add it in manually to the repos where you are working until we find a better solution.

**Comment by Tinkaa** [comment]
Okay, I will rest my case. 80 limit is alright for now (already got more used to it).

**Pull request closed without merging**
